#!/usr/bin/env python3
"""Generate responsive variants for post hero images.

Heroes never render wider than 640 CSS px (--measure is 40rem), so a
1600px original is mostly wasted bytes. This writes narrower copies
next to each original and records what exists in _data/image_variants.yml
so the template can build a srcset without ever pointing at a missing
file.

Safe to re-run. Variants are only rebuilt when the original is newer.
"""

import os
import re
import sys
import glob

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

IMAGE_DIR = os.path.join("assets", "images")
DATA_FILE = os.path.join("_data", "image_variants.yml")
POST_DIRS = ("_posts", "_queue")

# 640 covers DPR 1, 1280 covers DPR 2. 960 catches the awkward middle.
WIDTHS = (640, 960, 1280)
QUALITY = 82

# name-640.webp — used to recognise our own output so we never
# generate variants of variants.
VARIANT_RE = re.compile(r"-(\d+)$")


def referenced_images():
    """Hero images named in post front matter."""
    found = set()
    for d in POST_DIRS:
        for path in glob.glob(os.path.join(d, "*.md")):
            with open(path, encoding="utf-8") as fh:
                for line in fh:
                    m = re.match(r"^image:\s*(\S+)", line)
                    if m:
                        found.add(m.group(1).lstrip("/"))
    return found


def is_variant(stem):
    return bool(VARIANT_RE.search(stem))


def build(path):
    """Return the list of widths available for one original."""
    stem, ext = os.path.splitext(os.path.basename(path))
    if is_variant(stem):
        return None

    try:
        im = Image.open(path)
    except Exception as exc:
        print(f"  skip {path}: {exc}")
        return None

    im = im.convert("RGB")
    made = []
    src_mtime = os.path.getmtime(path)

    for w in WIDTHS:
        # Never upscale. A source smaller than the target is already fine.
        if w >= im.width:
            continue
        out = os.path.join(IMAGE_DIR, f"{stem}-{w}.webp")
        made.append(w)
        if os.path.exists(out) and os.path.getmtime(out) >= src_mtime:
            continue
        h = round(im.height * w / im.width)
        im.resize((w, h), Image.LANCZOS).save(
            out, "WEBP", quality=QUALITY, method=6
        )
        print(f"  wrote {os.path.basename(out)} ({os.path.getsize(out)//1024}K)")

    # The original is always the widest candidate.
    made.append(im.width)
    return sorted(set(made))


def main():
    wanted = referenced_images()
    if not wanted:
        print("No hero images referenced in posts.")

    manifest = {}
    print("Generating variants...")
    for path in sorted(glob.glob(os.path.join(IMAGE_DIR, "*"))):
        ext = os.path.splitext(path)[1].lower()
        if ext not in (".webp", ".jpg", ".jpeg", ".png"):
            continue
        rel = path.replace(os.sep, "/")
        # Only process images a post actually uses as a hero. Icons and
        # the social card have fixed sizes and must not be touched.
        if rel not in wanted:
            continue
        widths = build(path)
        if widths:
            stem = os.path.splitext(os.path.basename(path))[0]
            manifest[stem] = widths

    os.makedirs("_data", exist_ok=True)
    with open(DATA_FILE, "w", encoding="utf-8") as fh:
        fh.write("# Generated by .github/scripts/resize_images.py. Do not edit.\n")
        fh.write("# Maps an image stem to the widths available on disk.\n")
        for stem in sorted(manifest):
            fh.write(f"{stem}:\n")
            for w in manifest[stem]:
                fh.write(f"  - {w}\n")

    print(f"\nWrote {DATA_FILE} with {len(manifest)} image(s).")


if __name__ == "__main__":
    main()
